import { Project, Service, ServiceDetail, Skill, Translations, Language } from './types';
import { Server, Database, Globe, Terminal, Cpu, Smartphone, Cloud, Layout, ShieldCheck } from 'lucide-react';

export const WHATSAPP_NUMBER = '5584994349355';
export const LINKEDIN_URL = 'https://www.linkedin.com/in/jose-erilson-araujo-3265a52b1/';
export const GITHUB_URL = 'https://github.com/erilsonaraujo/ErilsonDigital';
export const EMAIL_ADDRESS = 'joseerilsonaraujo@gmail.com';
export const DISCORD_URL = 'https://discord.gg/3VDFU2wy';
export const INSTAGRAM_URL = 'https://instagram.com/josearaujo1986';

export const TRANSLATIONS: Record<Language, Translations> = {
  pt: {
    nav: {
      home: 'Home',
      services: 'Servicos',
      cases: 'Cases',
      process: 'Processo',
      about: 'Sobre',
      contact: 'Contato',
      booking: 'Agendar',
      themeToggle: 'Alternar tema',
      languageToggle: 'Selecionar idioma',
      menuToggle: 'Alternar menu',
    },
    hero: {
      badge: 'Consultoria em Engenharia & IA',
      title: 'Produtos digitais que escalam com autoridade',
      subtitle: 'Arquitetura de alto nivel, automacoes inteligentes e design premium para empresas que precisam de tecnologia confiavel e retorno real.',
      ctaPrimary: 'Agendar diagnostico',
      ctaSecondary: 'Ver cases',
      industriesLabel: 'Setores atendidos',
      industries: ['Fintech', 'SaaS B2B', 'Saude', 'Legal', 'E-commerce'],
      highlights: [
        { title: 'Seguranca', text: 'Governanca OWASP, compliance e controles de risco.' },
        { title: 'Escalabilidade', text: 'Arquiteturas prontas para alto volume e novos produtos.' },
        { title: 'Valor Premium', text: 'Entrega alinhada a posicionamento, margem e ROI.' },
      ],
      profileCards: [
        { label: 'Especialidades', value: 'IA aplicada, backends criticos, produtos premium' },
        { label: 'Foco', value: 'Solucao sob medida com eficiencia de capital' },
      ],
    },
    services: {
      title: 'Solucoes estrategicas para negocios ambiciosos',
      subtitle: 'Projetos de engenharia e produto digital pensados para velocidade, confianca e diferenca competitiva.',
      note: 'Servicos premium',
      cta: 'Explorar servico',
    },
    process: {
      title: 'Metodo de entrega premium',
      subtitle: 'Processo consultivo para reduzir risco, aumentar previsibilidade e acelerar resultados.',
      stepLabel: 'Etapa',
      steps: [
        { title: 'Diagnostico e estrategia', text: 'Mapeio de contexto, metas e riscos para um plano de acao assertivo.' },
        { title: 'Arquitetura e design', text: 'Blueprint tecnico, UX e jornada de conversao alinhados ao negocio.' },
        { title: 'Entrega e validacao', text: 'Desenvolvimento iterativo com qualidade, testes e governanca.' },
        { title: 'Escala e evolucao', text: 'Roadmap continuo para manter performance e vantagem competitiva.' },
      ],
    },
    projects: {
      title: 'Cases de alto impacto',
      subtitle: 'Solucoes reais que aumentam receita, reduzem custos e elevam o posicionamento de mercado.',
      challenge: 'Desafio',
      solution: 'Solucao',
      viewProject: 'Ver case',
    },
    testimonials: {
      title: 'Depoimentos',
      subtitle: 'Lideres que confiam na engenharia',
      lead: 'Resultados consistentes com parceria estrategica e execucao de alto nivel.',
    },
    booking: {
      label: 'Agenda',
      title: 'Agende uma consultoria estrategica',
      description: 'Sessao de 30 minutos para entender seu momento, validar a viabilidade e propor o melhor caminho.',
      ctaPrimary: 'Reservar horario',
      ctaSecondary: 'Falar no WhatsApp',
      items: [
        'Diagnostico rapido do seu contexto e objetivos.',
        'Plano inicial com prioridades, riscos e entregas.',
        'Alinhamento de budget, prazos e proxima etapa.',
      ],
      form: {
        dateLabel: 'Data preferida',
        timeLabel: 'Horario preferido',
      },
      successTitle: 'Solicitacao enviada',
      successDescription: 'Em instantes entrarei em contato para confirmar o melhor horario.',
      error: 'Ocorreu um erro ao processar. Tente novamente.',
    },
    about: {
      label: 'Sobre',
      headline: 'Engenharia com visao de negocio e padrao global',
      description: 'Trabalho com empresas que precisam de tecnologia segura, escalavel e com alto valor percebido. Entrego estrutura, execucao e estrategia para projetos de alto ticket.',
      highlights: [
        { title: 'Visao executiva', text: 'Decisoes guiadas por impacto, risco e ROI.' },
        { title: 'Qualidade enterprise', text: 'Padroes internacionais de arquitetura e seguranca.' },
        { title: 'Entrega consultiva', text: 'Comunicacao direta e alinhamento continuo.' },
        { title: 'Crescimento sustentavel', text: 'Produtos preparados para evoluir sem retrabalho.' },
      ],
      ctaPrimary: 'Falar com o especialista',
      ctaSecondary: 'Agendar conversa',
      stackLabel: 'Stack estrategica',
    },
    contact: {
      title: 'Contato',
      subtitle: 'Vamos falar sobre seu projeto',
      description: 'Responda ao briefing e eu retorno com o melhor plano de acao para o seu negocio.',
      labels: {
        name: 'Seu nome',
        email: 'Email corporativo',
        phone: 'WhatsApp',
        company: 'Empresa',
        projectType: 'Tipo de projeto',
        budget: 'Budget estimado (R$)',
        timeline: 'Prazo desejado',
        message: 'Descreva o desafio',
      },
      projectOptions: ['Selecione', 'Produto digital', 'IA e automacao', 'Backend enterprise', 'Dados e analytics', 'Cloud e DevOps', 'Outro'],
      budgetOptions: ['Selecione', '50-100k', '100-200k', '200-500k', '500k+'],
      timelineOptions: ['Selecione', 'Ate 30 dias', '30-60 dias', '60-90 dias', '90+ dias'],
      cta: 'Enviar briefing',
      ctaSending: 'Enviando...',
      ctaSent: 'Enviado!',
      success: 'Briefing enviado. Retorno em ate 24h.',
      error: 'Erro ao enviar. Tente novamente.',
      whatsapp: 'Chamar no WhatsApp',
      infoLocation: 'Natal, RN - Brasil (Remoto / Hibrido)',
    },
    ai: {
      name: 'Sofia',
      role: 'Assistente estrategica',
      status: 'Disponivel',
      errorFallback: 'Tive um pequeno lapso tecnico. Pode repetir sua ultima frase?',
      conversationTitle: 'Conversa com Sofia - Erilson Digital',
      conversationUserLabel: 'Voce',
      conversationAssistantLabel: 'Sofia',
      subtitle: 'Ola! Sou a Sofia, assistente do Erilson. Ele esta focado em codigo agora, mas posso ajudar com detalhes de servicos, cases e processo.',
      disclaimer: 'Sofia: Assistente virtual estrategica do Erilson Digital',
      suggestions: ['Quanto custa desenvolver um MVP?', 'Voce oferece suporte apos a entrega?', 'Qual stack recomenda para minha startup?'],
      helpLabel: 'Perguntas rapidas',
      placeholder: 'Digite sua pergunta...',
      bookingCta: 'Agendar consultoria',
      whatsappCta: 'Continuar no WhatsApp',
    },
    servicePage: {
      outcomesLabel: 'Resultados esperados',
      deliverablesLabel: 'Entregaveis',
      timelineLabel: 'Prazo',
      stackLabel: 'Stack',
      idealForLabel: 'Ideal para',
    },
  },
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      cases: 'Cases',
      process: 'Process',
      about: 'About',
      contact: 'Contact',
      booking: 'Book',
      themeToggle: 'Toggle theme',
      languageToggle: 'Select language',
      menuToggle: 'Toggle menu',
    },
    hero: {
      badge: 'Engineering & AI Consulting',
      title: 'Digital products built to scale with authority',
      subtitle: 'High-end architecture, intelligent automation, and premium design for companies that need reliable tech and real ROI.',
      ctaPrimary: 'Book a diagnostic call',
      ctaSecondary: 'View cases',
      industriesLabel: 'Industries served',
      industries: ['Fintech', 'B2B SaaS', 'Healthcare', 'Legal', 'E-commerce'],
      highlights: [
        { title: 'Security', text: 'OWASP governance, compliance, and risk controls.' },
        { title: 'Scalability', text: 'Architecture ready for growth and new products.' },
        { title: 'Premium Value', text: 'Delivery aligned with positioning, margin, and ROI.' },
      ],
      profileCards: [
        { label: 'Specialties', value: 'Applied AI, critical backends, premium products' },
        { label: 'Focus', value: 'Tailored solutions with capital efficiency' },
      ],
    },
    services: {
      title: 'Strategic solutions for ambitious companies',
      subtitle: 'Engineering and product programs built for speed, trust, and competitive differentiation.',
      note: 'Premium services',
      cta: 'Explore service',
    },
    process: {
      title: 'Premium delivery method',
      subtitle: 'A consultative process to reduce risk, improve predictability, and accelerate results.',
      stepLabel: 'Step',
      steps: [
        { title: 'Diagnosis and strategy', text: 'We map context, goals, and risks to define an assertive plan.' },
        { title: 'Architecture and design', text: 'Technical blueprint, UX, and conversion journey aligned with business.' },
        { title: 'Delivery and validation', text: 'Iterative builds with quality, testing, and governance.' },
        { title: 'Scale and evolution', text: 'Continuous roadmap to maintain performance and advantage.' },
      ],
    },
    projects: {
      title: 'High-impact cases',
      subtitle: 'Real solutions that increase revenue, reduce costs, and elevate market positioning.',
      challenge: 'Challenge',
      solution: 'Solution',
      viewProject: 'View case',
    },
    testimonials: {
      title: 'Testimonials',
      subtitle: 'Leaders who trust the engineering',
      lead: 'Consistent results through strategic partnership and top-tier execution.',
    },
    booking: {
      label: 'Booking',
      title: 'Book a strategic consultation',
      description: 'A 30-minute session to understand your context, validate feasibility, and outline the best path forward.',
      ctaPrimary: 'Reserve a slot',
      ctaSecondary: 'Talk on WhatsApp',
      items: [
        'Quick diagnosis of your context and objectives.',
        'Initial plan with priorities, risks, and deliverables.',
        'Alignment on budget, timeline, and next steps.',
      ],
      form: {
        dateLabel: 'Preferred date',
        timeLabel: 'Preferred time',
      },
      successTitle: 'Request sent',
      successDescription: 'I will get back shortly to confirm the best time.',
      error: 'Something went wrong. Please try again.',
    },
    about: {
      label: 'About',
      headline: 'Engineering with business vision and global standards',
      description: 'I work with companies that need secure, scalable technology with high perceived value. Strategy, execution, and structure for high-ticket projects.',
      highlights: [
        { title: 'Executive vision', text: 'Decisions guided by impact, risk, and ROI.' },
        { title: 'Enterprise quality', text: 'International architecture and security standards.' },
        { title: 'Consultative delivery', text: 'Direct communication and continuous alignment.' },
        { title: 'Sustainable growth', text: 'Products prepared to evolve without rework.' },
      ],
      ctaPrimary: 'Talk to the specialist',
      ctaSecondary: 'Book a call',
      stackLabel: 'Strategic stack',
    },
    contact: {
      title: 'Contact',
      subtitle: 'Let’s talk about your project',
      description: 'Share the briefing and I will respond with the best plan for your business.',
      labels: {
        name: 'Your name',
        email: 'Work email',
        phone: 'WhatsApp',
        company: 'Company',
        projectType: 'Project type',
        budget: 'Estimated budget (USD)',
        timeline: 'Desired timeline',
        message: 'Describe the challenge',
      },
      projectOptions: ['Select', 'Digital product', 'AI and automation', 'Enterprise backend', 'Data and analytics', 'Cloud and DevOps', 'Other'],
      budgetOptions: ['Select', '50-100k', '100-200k', '200-500k', '500k+'],
      timelineOptions: ['Select', 'Up to 30 days', '30-60 days', '60-90 days', '90+ days'],
      cta: 'Send briefing',
      ctaSending: 'Sending...',
      ctaSent: 'Sent!',
      success: 'Briefing sent. Response within 24h.',
      error: 'Failed to send. Please try again.',
      whatsapp: 'Chat on WhatsApp',
      infoLocation: 'Natal, Brazil (Remote / Hybrid)',
    },
    ai: {
      name: 'Sofia',
      role: 'Strategic assistant',
      status: 'Available',
      errorFallback: 'I had a small technical hiccup. Could you repeat your last message?',
      conversationTitle: 'Conversation with Sofia - Erilson Digital',
      conversationUserLabel: 'You',
      conversationAssistantLabel: 'Sofia',
      subtitle: 'Hi! I am Sofia, Erilson’s assistant. He is focused on code right now, but I can help with services, cases, and process details.',
      disclaimer: 'Sofia: Erilson Digital strategic virtual assistant',
      suggestions: ['How much does an MVP cost?', 'Do you offer support after delivery?', 'What stack fits my startup?'],
      helpLabel: 'Quick questions',
      placeholder: 'Type your question...',
      bookingCta: 'Book a consultation',
      whatsappCta: 'Continue on WhatsApp',
    },
    servicePage: {
      outcomesLabel: 'Expected outcomes',
      deliverablesLabel: 'Deliverables',
      timelineLabel: 'Timeline',
      stackLabel: 'Stack',
      idealForLabel: 'Ideal for',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      cases: 'Casos',
      process: 'Proceso',
      about: 'Sobre mi',
      contact: 'Contacto',
      booking: 'Agendar',
      themeToggle: 'Cambiar tema',
      languageToggle: 'Seleccionar idioma',
      menuToggle: 'Alternar menu',
    },
    hero: {
      badge: 'Consultoria en Ingenieria e IA',
      title: 'Productos digitales que escalan con autoridad',
      subtitle: 'Arquitectura de alto nivel, automatizacion inteligente y diseno premium para empresas que necesitan tecnologia confiable y ROI real.',
      ctaPrimary: 'Agendar diagnostico',
      ctaSecondary: 'Ver casos',
      industriesLabel: 'Sectores atendidos',
      industries: ['Fintech', 'SaaS B2B', 'Salud', 'Legal', 'E-commerce'],
      highlights: [
        { title: 'Seguridad', text: 'Gobernanza OWASP, compliance y control de riesgos.' },
        { title: 'Escalabilidad', text: 'Arquitectura lista para crecer y nuevos productos.' },
        { title: 'Valor Premium', text: 'Entrega alineada a posicionamiento, margen y ROI.' },
      ],
      profileCards: [
        { label: 'Especialidades', value: 'IA aplicada, backends criticos, productos premium' },
        { label: 'Enfoque', value: 'Soluciones a medida con eficiencia de capital' },
      ],
    },
    services: {
      title: 'Soluciones estrategicas para negocios ambiciosos',
      subtitle: 'Programas de ingenieria y producto digital para velocidad, confianza y diferenciacion competitiva.',
      note: 'Servicios premium',
      cta: 'Explorar servicio',
    },
    process: {
      title: 'Metodo de entrega premium',
      subtitle: 'Proceso consultivo para reducir riesgo, aumentar previsibilidad y acelerar resultados.',
      stepLabel: 'Etapa',
      steps: [
        { title: 'Diagnostico y estrategia', text: 'Mapeamos contexto, metas y riesgos para un plan claro.' },
        { title: 'Arquitectura y diseno', text: 'Blueprint tecnico, UX y conversion alineados al negocio.' },
        { title: 'Entrega y validacion', text: 'Desarrollo iterativo con calidad, pruebas y gobernanza.' },
        { title: 'Escala y evolucion', text: 'Roadmap continuo para mantener performance y ventaja.' },
      ],
    },
    projects: {
      title: 'Casos de alto impacto',
      subtitle: 'Soluciones reales que aumentan ingresos, reducen costos y elevan el posicionamiento.',
      challenge: 'Desafio',
      solution: 'Solucion',
      viewProject: 'Ver caso',
    },
    testimonials: {
      title: 'Testimonios',
      subtitle: 'Lideres que confian en la ingenieria',
      lead: 'Resultados consistentes con alianza estrategica y ejecucion de alto nivel.',
    },
    booking: {
      label: 'Agenda',
      title: 'Agenda una consultoria estrategica',
      description: 'Sesion de 30 minutos para entender tu contexto, validar viabilidad y definir el mejor camino.',
      ctaPrimary: 'Reservar horario',
      ctaSecondary: 'Hablar por WhatsApp',
      items: [
        'Diagnostico rapido de tu contexto y objetivos.',
        'Plan inicial con prioridades, riesgos y entregables.',
        'Alineacion de presupuesto, tiempos y proxima etapa.',
      ],
      form: {
        dateLabel: 'Fecha preferida',
        timeLabel: 'Horario preferido',
      },
      successTitle: 'Solicitud enviada',
      successDescription: 'En breve respondere para confirmar el mejor horario.',
      error: 'Ocurrio un error. Intenta nuevamente.',
    },
    about: {
      label: 'Sobre mi',
      headline: 'Ingenieria con vision de negocio y estandar global',
      description: 'Trabajo con empresas que necesitan tecnologia segura, escalable y con alto valor percibido. Estrategia, ejecucion y estructura para proyectos high-ticket.',
      highlights: [
        { title: 'Vision ejecutiva', text: 'Decisiones guiadas por impacto, riesgo y ROI.' },
        { title: 'Calidad enterprise', text: 'Estandares internacionales de arquitectura y seguridad.' },
        { title: 'Entrega consultiva', text: 'Comunicacion directa y alineacion continua.' },
        { title: 'Crecimiento sostenible', text: 'Productos listos para evolucionar sin retrabajo.' },
      ],
      ctaPrimary: 'Hablar con el especialista',
      ctaSecondary: 'Agendar llamada',
      stackLabel: 'Stack estrategico',
    },
    contact: {
      title: 'Contacto',
      subtitle: 'Hablemos de tu proyecto',
      description: 'Completa el briefing y respondere con el mejor plan para tu negocio.',
      labels: {
        name: 'Tu nombre',
        email: 'Email corporativo',
        phone: 'WhatsApp',
        company: 'Empresa',
        projectType: 'Tipo de proyecto',
        budget: 'Presupuesto estimado (USD)',
        timeline: 'Plazo deseado',
        message: 'Describe el desafio',
      },
      projectOptions: ['Selecciona', 'Producto digital', 'IA y automatizacion', 'Backend enterprise', 'Datos y analytics', 'Cloud y DevOps', 'Otro'],
      budgetOptions: ['Selecciona', '50-100k', '100-200k', '200-500k', '500k+'],
      timelineOptions: ['Selecciona', 'Hasta 30 dias', '30-60 dias', '60-90 dias', '90+ dias'],
      cta: 'Enviar briefing',
      ctaSending: 'Enviando...',
      ctaSent: 'Enviado!',
      success: 'Briefing enviado. Respuesta en 24h.',
      error: 'Error al enviar. Intenta nuevamente.',
      whatsapp: 'Hablar por WhatsApp',
      infoLocation: 'Natal, Brasil (Remoto / Hibrido)',
    },
    ai: {
      name: 'Sofia',
      role: 'Asistente estrategica',
      status: 'Disponible',
      errorFallback: 'Tuve un pequeno inconveniente tecnico. Puedes repetir tu ultimo mensaje?',
      conversationTitle: 'Conversacion con Sofia - Erilson Digital',
      conversationUserLabel: 'Tu',
      conversationAssistantLabel: 'Sofia',
      subtitle: 'Hola! Soy Sofia, asistente de Erilson. El esta enfocado en codigo ahora, pero puedo ayudar con servicios, casos y proceso.',
      disclaimer: 'Sofia: Asistente virtual estrategica de Erilson Digital',
      suggestions: ['Cuanto cuesta un MVP?', 'Ofreces soporte despues de la entrega?', 'Que stack recomiendas para mi startup?'],
      helpLabel: 'Preguntas rapidas',
      placeholder: 'Escribe tu pregunta...',
      bookingCta: 'Agendar consultoria',
      whatsappCta: 'Continuar en WhatsApp',
    },
    servicePage: {
      outcomesLabel: 'Resultados esperados',
      deliverablesLabel: 'Entregables',
      timelineLabel: 'Plazo',
      stackLabel: 'Stack',
      idealForLabel: 'Ideal para',
    },
  },
};

export const SERVICES: Service[] = [
  {
    id: 'ai-automation',
    title: 'Automacao e IA Aplicada',
    description: 'Automatize operacoes criticas com agentes inteligentes e dados acionaveis.',
    icon: Cpu,
  },
  {
    id: 'enterprise-backend',
    title: 'Backends Enterprise',
    description: 'Arquitetura resiliente, APIs seguras e sistemas prontos para escala.',
    icon: Server,
  },
  {
    id: 'product-engineering',
    title: 'Produto Digital Premium',
    description: 'Experiencias web e SaaS com UX refinado e performance.',
    icon: Layout,
  },
  {
    id: 'ai-agents',
    title: 'Agentes Inteligentes',
    description: 'Sistemas autonomos que tomam decisoes e operam com confiabilidade.',
    icon: Terminal,
  },
  {
    id: 'automation-ops',
    title: 'Operacoes Automatizadas',
    description: 'Integracoes e automacoes ponta a ponta sem friccao.',
    icon: Globe,
  },
  {
    id: 'data-platforms',
    title: 'Dados & Observabilidade',
    description: 'Dashboards executivos, analytics e monitoramento.',
    icon: Smartphone,
  },
  {
    id: 'cloud',
    title: 'Cloud, DevOps e SRE',
    description: 'Infra resiliente, CI/CD seguro e governanca de deploy.',
    icon: Cloud,
  },
  {
    id: 'security',
    title: 'Seguranca & LGPD',
    description: 'Hardening, auditorias e controles para operacoes criticas.',
    icon: ShieldCheck,
  },
];

export const SERVICES_I18N: Record<Language, Array<Pick<Service, 'id' | 'title' | 'description'>>> = {
  pt: [
    { id: 'ai-automation', title: 'Automacao e IA Aplicada', description: 'Automatize operacoes criticas com agentes inteligentes e dados acionaveis.' },
    { id: 'enterprise-backend', title: 'Backends Enterprise', description: 'Arquitetura resiliente, APIs seguras e sistemas transacionais prontos para escala.' },
    { id: 'product-engineering', title: 'Produto Digital Premium', description: 'Experiencias web e SaaS com UX refinado, performance e narrativa de alto valor.' },
    { id: 'ai-agents', title: 'Agentes Inteligentes', description: 'Sistemas autonomos que tomam decisoes e operam com alta confiabilidade.' },
    { id: 'automation-ops', title: 'Operacoes Automatizadas', description: 'Fluxos operacionais sem friccao, integracoes e automacoes ponta a ponta.' },
    { id: 'data-platforms', title: 'Dados & Observabilidade', description: 'Dashboards executivos, analytics e monitoramento avancado para decisao.' },
    { id: 'cloud', title: 'Cloud, DevOps e SRE', description: 'Infraestrutura resiliente, CI/CD seguro e governanca de deploy.' },
    { id: 'security', title: 'Seguranca & LGPD', description: 'Revisoes, threat modeling e controles para operacoes criticas.' },
  ],
  en: [
    { id: 'ai-automation', title: 'Applied AI & Automation', description: 'Automate critical operations with intelligent agents and actionable data.' },
    { id: 'enterprise-backend', title: 'Enterprise Backends', description: 'Resilient architecture, secure APIs, and transaction-ready systems.' },
    { id: 'product-engineering', title: 'Premium Digital Products', description: 'Web and SaaS experiences with refined UX, performance, and premium storytelling.' },
    { id: 'ai-agents', title: 'Intelligent Agents', description: 'Autonomous systems that make decisions with high reliability.' },
    { id: 'automation-ops', title: 'Automated Operations', description: 'End-to-end integrations and workflows without friction.' },
    { id: 'data-platforms', title: 'Data & Observability', description: 'Executive dashboards, analytics, and advanced monitoring for decisions.' },
    { id: 'cloud', title: 'Cloud, DevOps & SRE', description: 'Resilient infrastructure, secure CI/CD, and deployment governance.' },
    { id: 'security', title: 'Security & Compliance', description: 'Audits, threat modeling, and controls for critical operations.' },
  ],
  es: [
    { id: 'ai-automation', title: 'IA y Automatizacion Aplicada', description: 'Automatiza operaciones criticas con agentes inteligentes y datos accionables.' },
    { id: 'enterprise-backend', title: 'Backends Enterprise', description: 'Arquitectura resiliente, APIs seguras y sistemas listos para escalar.' },
    { id: 'product-engineering', title: 'Producto Digital Premium', description: 'Experiencias web y SaaS con UX refinado, performance y narrativa premium.' },
    { id: 'ai-agents', title: 'Agentes Inteligentes', description: 'Sistemas autonomos que toman decisiones con alta confiabilidad.' },
    { id: 'automation-ops', title: 'Operaciones Automatizadas', description: 'Integraciones y automatizaciones de punta a punta sin friccion.' },
    { id: 'data-platforms', title: 'Datos y Observabilidad', description: 'Dashboards ejecutivos, analytics y monitoreo avanzado.' },
    { id: 'cloud', title: 'Cloud, DevOps y SRE', description: 'Infraestructura resiliente, CI/CD seguro y gobernanza de despliegue.' },
    { id: 'security', title: 'Seguridad y Compliance', description: 'Auditorias, threat modeling y controles para operaciones criticas.' },
  ],
};

export const SERVICE_DETAILS_BY_LANG: Record<Language, ServiceDetail[]> = {
  pt: [
    {
      id: 'ai-automation',
      title: 'Automacao e IA Aplicada',
      summary: 'Fluxos autonomos, agentes inteligentes e automacao com governanca.',
      description: 'Projetos de IA aplicados ao negocio com foco em eficiencia operacional, aumento de receita e reducao de custos. A IA entra como motor de decisao, nao como experimento.',
      outcomes: [
        'Automacao de processos repetitivos com alta confiabilidade',
        'Reducao de tempo operacional e ganho de escala',
        'Assistentes inteligentes orientados a conversao',
      ],
      deliverables: [
        'Mapeamento e blueprint de automacao',
        'Agentes inteligentes treinados para fluxos reais',
        'Dashboards de performance e qualidade',
        'Documentacao tecnica e operacional',
      ],
      timeline: '6 a 10 semanas',
      suitableFor: ['Operacoes com alto volume', 'Times comerciais e suporte', 'Negocios data-driven'],
      stack: ['Python', 'Gemini / OpenAI', 'Workflows customizados', 'APIs internas'],
      image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'enterprise-backend',
      title: 'Backends Enterprise',
      summary: 'APIs seguras e arquitetura resiliente para sistemas criticos.',
      description: 'Backends preparados para alta demanda, integracoes complexas e compliance. Ideal para produtos que precisam de estabilidade e confianca absoluta.',
      outcomes: [
        'Infraestrutura segura e auditavel',
        'Performance previsivel em picos de demanda',
        'Governanca tecnica para squads escalaveis',
      ],
      deliverables: [
        'Arquitetura e modelagem de dominio',
        'APIs REST ou GraphQL com testes completos',
        'Observabilidade e monitoramento',
        'Guia de escalabilidade e roadmap tecnico',
      ],
      timeline: '8 a 12 semanas',
      suitableFor: ['Fintechs', 'Plataformas SaaS', 'Sistemas financeiros e juridicos'],
      stack: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'Kubernetes'],
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'product-engineering',
      title: 'Produto Digital Premium',
      summary: 'Experiencias digitais premium com foco em conversao.',
      description: 'Construcao de produtos e plataformas digitais que comunicam valor alto e vendem com autoridade. Design, UX e engenharia operando em conjunto.',
      outcomes: [
        'Percepcao de valor premium imediata',
        'Conversao com UX sofisticado e fluido',
        'Performance e acessibilidade de nivel global',
      ],
      deliverables: [
        'Arquitetura de informacao e UX flows',
        'Design system premium customizado',
        'Implementacao Next.js e performance tuning',
        'Assets visuais e motion guidelines',
      ],
      timeline: '6 a 9 semanas',
      suitableFor: ['Consultorias premium', 'Produtos B2B', 'Marcas high-ticket'],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
      image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'ai-agents',
      title: 'Agentes Inteligentes',
      summary: 'Autonomia operacional com agentes especializados.',
      description: 'Agentes focados em vendas, suporte ou operacoes. Processos que antes demandavam equipe agora passam a rodar de forma controlada e previsivel.',
      outcomes: [
        'Escala sem aumento proporcional de equipe',
        'Respostas consistentes e em tempo real',
        'Coleta de dados para melhoria continua',
      ],
      deliverables: [
        'Arquitetura de agentes com memoria e contexto',
        'Treinamento em dados proprietarios',
        'Monitoramento e guardrails de qualidade',
        'Relatorios de conversao e eficiencia',
      ],
      timeline: '5 a 8 semanas',
      suitableFor: ['Suporte 24/7', 'Times comerciais', 'Operacoes com SLA alto'],
      stack: ['Python', 'Node.js', 'LLM Orchestration', 'PostgreSQL'],
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'automation-ops',
      title: 'Operacoes Automatizadas',
      summary: 'Processos internos com alta eficiencia e controle.',
      description: 'Integre sistemas, elimine retrabalho e crie fluxos que rodam sozinhos com rastreabilidade total.',
      outcomes: [
        'Operacoes com menos custos e mais previsibilidade',
        'Integracoes seguras entre sistemas legados',
        'Monitoramento com alertas inteligentes',
      ],
      deliverables: [
        'Mapeamento de processos',
        'Workflows e integracoes customizadas',
        'Dashboards de KPI e alertas',
        'Documentacao e treinamento da equipe',
      ],
      timeline: '4 a 7 semanas',
      suitableFor: ['Times operacionais', 'Backoffice financeiro', 'Escala comercial'],
      stack: ['Node.js', 'Python', 'APIs privadas', 'Mensageria'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'data-platforms',
      title: 'Dados & Observabilidade',
      summary: 'Analytics estrategico para lideranca e growth.',
      description: 'Dashboards executivos, inteligencia de negocio e monitoramento de performance para decisao rapida.',
      outcomes: [
        'Visibilidade total da operacao',
        'Analises com base em dados confiaveis',
        'Alertas automatizados para riscos',
      ],
      deliverables: [
        'Modelagem de dados e pipelines',
        'Dashboards customizados',
        'Eventos de conversao configurados',
        'Documentacao e governanca',
      ],
      timeline: '5 a 8 semanas',
      suitableFor: ['Marketing e growth', 'Executivos', 'Produto e operacoes'],
      stack: ['PostgreSQL', 'Metabase', 'Umami', 'Event tracking'],
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'cloud',
      title: 'Cloud, DevOps e SRE',
      summary: 'Infra segura, deploys confiaveis e escala real.',
      description: 'Infraestrutura moderna com CI/CD, observabilidade e resiliencia. Tudo pensado para reduzir downtime e riscos.',
      outcomes: [
        'Menos downtime e incidentes',
        'Deploys previsiveis e auditaveis',
        'Performance e custos sob controle',
      ],
      deliverables: [
        'Arquitetura cloud e infraestrutura como codigo',
        'Pipelines de CI/CD com validacoes',
        'Monitoramento e alertas',
        'Documentacao e handover',
      ],
      timeline: '4 a 6 semanas',
      suitableFor: ['SaaS em crescimento', 'Times de engenharia', 'Produtos mission-critical'],
      stack: ['AWS', 'Docker', 'GitHub Actions', 'Terraform'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'security',
      title: 'Seguranca & LGPD',
      summary: 'Governanca tecnica e protecao nivel enterprise.',
      description: 'Auditorias, hardening e adequacao LGPD com foco em mitigacao de riscos e confianca para stakeholders.',
      outcomes: [
        'Reducao de vulnerabilidades criticas',
        'Conformidade com exigencias regulatorias',
        'Planos de mitigacao e resposta',
      ],
      deliverables: [
        'Assessment de risco OWASP',
        'Plano de hardening e correcoes',
        'Politicas e documentacao LGPD',
        'Relatorios executivos',
      ],
      timeline: '3 a 5 semanas',
      suitableFor: ['Empresas reguladas', 'Times juridicos', 'Produtos com dados sensiveis'],
      stack: ['OWASP', 'DevSecOps', 'LGPD', 'Threat modeling'],
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1600',
    },
  ],
  en: [
    {
      id: 'ai-automation',
      title: 'Applied AI & Automation',
      summary: 'Autonomous flows, intelligent agents, and governed automation.',
      description: 'AI projects focused on operational efficiency, revenue growth, and cost reduction. AI becomes a decision engine, not an experiment.',
      outcomes: [
        'Automation of repetitive processes with high reliability',
        'Operational time reduction and scalable output',
        'Intelligent assistants oriented to conversion',
      ],
      deliverables: [
        'Automation mapping and blueprint',
        'Intelligent agents trained for real workflows',
        'Performance and quality dashboards',
        'Technical and operational documentation',
      ],
      timeline: '6 to 10 weeks',
      suitableFor: ['High-volume operations', 'Sales and support teams', 'Data-driven businesses'],
      stack: ['Python', 'Gemini / OpenAI', 'Custom workflows', 'Internal APIs'],
      image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'enterprise-backend',
      title: 'Enterprise Backends',
      summary: 'Secure APIs and resilient architecture for critical systems.',
      description: 'Backends prepared for high demand, complex integrations, and compliance. Ideal for products that require absolute stability.',
      outcomes: [
        'Secure and auditable infrastructure',
        'Predictable performance during demand spikes',
        'Technical governance for scalable squads',
      ],
      deliverables: [
        'Architecture and domain modeling',
        'REST or GraphQL APIs with full test coverage',
        'Observability and monitoring',
        'Scalability guide and technical roadmap',
      ],
      timeline: '8 to 12 weeks',
      suitableFor: ['Fintechs', 'SaaS platforms', 'Financial and legal systems'],
      stack: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'Kubernetes'],
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'product-engineering',
      title: 'Premium Digital Products',
      summary: 'Premium digital experiences focused on conversion.',
      description: 'Products and platforms that communicate high value and sell with authority. Design, UX, and engineering in one flow.',
      outcomes: [
        'Immediate premium value perception',
        'Conversion with sophisticated, fluid UX',
        'Global-grade performance and accessibility',
      ],
      deliverables: [
        'Information architecture and UX flows',
        'Custom premium design system',
        'Next.js implementation and performance tuning',
        'Visual assets and motion guidelines',
      ],
      timeline: '6 to 9 weeks',
      suitableFor: ['Premium consultancies', 'B2B products', 'High-ticket brands'],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
      image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'ai-agents',
      title: 'Intelligent Agents',
      summary: 'Operational autonomy with specialized agents.',
      description: 'Agents focused on sales, support, or operations. Processes that once required teams now run in a controlled, predictable way.',
      outcomes: [
        'Scale without proportional headcount growth',
        'Consistent responses in real time',
        'Data collection for continuous improvement',
      ],
      deliverables: [
        'Agent architecture with memory and context',
        'Training on proprietary data',
        'Quality monitoring and guardrails',
        'Conversion and efficiency reports',
      ],
      timeline: '5 to 8 weeks',
      suitableFor: ['24/7 support', 'Sales teams', 'Operations with strict SLAs'],
      stack: ['Python', 'Node.js', 'LLM orchestration', 'PostgreSQL'],
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'automation-ops',
      title: 'Automated Operations',
      summary: 'Internal processes with high efficiency and control.',
      description: 'Integrate systems, eliminate rework, and create flows that run on their own with full traceability.',
      outcomes: [
        'Operations with lower costs and higher predictability',
        'Secure integrations between legacy systems',
        'Monitoring with intelligent alerts',
      ],
      deliverables: [
        'Process mapping',
        'Custom workflows and integrations',
        'KPI dashboards and alerts',
        'Documentation and team enablement',
      ],
      timeline: '4 to 7 weeks',
      suitableFor: ['Operations teams', 'Finance back office', 'Commercial scale'],
      stack: ['Node.js', 'Python', 'Private APIs', 'Messaging'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'data-platforms',
      title: 'Data & Observability',
      summary: 'Strategic analytics for leadership and growth.',
      description: 'Executive dashboards, business intelligence, and performance monitoring for rapid decisions.',
      outcomes: [
        'Full visibility of operations',
        'Analysis based on trustworthy data',
        'Automated alerts for risks',
      ],
      deliverables: [
        'Data modeling and pipelines',
        'Custom dashboards',
        'Conversion events configured',
        'Documentation and governance',
      ],
      timeline: '5 to 8 weeks',
      suitableFor: ['Marketing and growth', 'Executives', 'Product and operations'],
      stack: ['PostgreSQL', 'Metabase', 'Umami', 'Event tracking'],
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'cloud',
      title: 'Cloud, DevOps & SRE',
      summary: 'Secure infrastructure, reliable deployments, and real scale.',
      description: 'Modern infrastructure with CI/CD, observability, and resilience. Designed to reduce downtime and risk.',
      outcomes: [
        'Less downtime and fewer incidents',
        'Predictable, auditable deployments',
        'Performance and cost control',
      ],
      deliverables: [
        'Cloud architecture and infrastructure as code',
        'CI/CD pipelines with validations',
        'Monitoring and alerts',
        'Documentation and handover',
      ],
      timeline: '4 to 6 weeks',
      suitableFor: ['Growing SaaS', 'Engineering teams', 'Mission-critical products'],
      stack: ['AWS', 'Docker', 'GitHub Actions', 'Terraform'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'security',
      title: 'Security & Compliance',
      summary: 'Technical governance and enterprise-grade protection.',
      description: 'Audits, hardening, and compliance focus to mitigate risk and build stakeholder trust.',
      outcomes: [
        'Reduced critical vulnerabilities',
        'Compliance with regulatory requirements',
        'Mitigation and incident response plans',
      ],
      deliverables: [
        'OWASP risk assessment',
        'Hardening plan and fixes',
        'Compliance policies and documentation',
        'Executive reports',
      ],
      timeline: '3 to 5 weeks',
      suitableFor: ['Regulated companies', 'Legal teams', 'Products with sensitive data'],
      stack: ['OWASP', 'DevSecOps', 'Compliance', 'Threat modeling'],
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1600',
    },
  ],
  es: [
    {
      id: 'ai-automation',
      title: 'IA y Automatizacion Aplicada',
      summary: 'Flujos autonomos, agentes inteligentes y automatizacion con gobernanza.',
      description: 'Proyectos de IA enfocados en eficiencia operativa, crecimiento de ingresos y reduccion de costos. La IA es motor de decision, no experimento.',
      outcomes: [
        'Automatizacion de procesos repetitivos con alta confiabilidad',
        'Reduccion de tiempo operativo y mayor escala',
        'Asistentes inteligentes orientados a conversion',
      ],
      deliverables: [
        'Mapeo y blueprint de automatizacion',
        'Agentes inteligentes entrenados para flujos reales',
        'Dashboards de performance y calidad',
        'Documentacion tecnica y operativa',
      ],
      timeline: '6 a 10 semanas',
      suitableFor: ['Operaciones con alto volumen', 'Equipos comerciales y soporte', 'Negocios data-driven'],
      stack: ['Python', 'Gemini / OpenAI', 'Workflows personalizados', 'APIs internas'],
      image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'enterprise-backend',
      title: 'Backends Enterprise',
      summary: 'APIs seguras y arquitectura resiliente para sistemas criticos.',
      description: 'Backends preparados para alta demanda, integraciones complejas y compliance. Ideal para productos que requieren estabilidad absoluta.',
      outcomes: [
        'Infraestructura segura y auditable',
        'Performance previsible en picos de demanda',
        'Gobernanza tecnica para equipos escalables',
      ],
      deliverables: [
        'Arquitectura y modelado de dominio',
        'APIs REST o GraphQL con pruebas completas',
        'Observabilidad y monitoreo',
        'Guia de escalabilidad y roadmap tecnico',
      ],
      timeline: '8 a 12 semanas',
      suitableFor: ['Fintechs', 'Plataformas SaaS', 'Sistemas financieros y legales'],
      stack: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'Kubernetes'],
      image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'product-engineering',
      title: 'Producto Digital Premium',
      summary: 'Experiencias digitales premium con foco en conversion.',
      description: 'Productos y plataformas que comunican alto valor y venden con autoridad. Diseno, UX e ingenieria en un solo flujo.',
      outcomes: [
        'Percepcion premium inmediata',
        'Conversion con UX sofisticado y fluido',
        'Performance y accesibilidad de nivel global',
      ],
      deliverables: [
        'Arquitectura de informacion y UX flows',
        'Design system premium personalizado',
        'Implementacion Next.js y performance tuning',
        'Assets visuales y motion guidelines',
      ],
      timeline: '6 a 9 semanas',
      suitableFor: ['Consultorias premium', 'Productos B2B', 'Marcas high-ticket'],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
      image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'ai-agents',
      title: 'Agentes Inteligentes',
      summary: 'Autonomia operativa con agentes especializados.',
      description: 'Agentes enfocados en ventas, soporte u operaciones. Procesos que antes requerian equipo ahora corren de forma controlada y predecible.',
      outcomes: [
        'Escala sin aumento proporcional de equipo',
        'Respuestas consistentes en tiempo real',
        'Datos para mejora continua',
      ],
      deliverables: [
        'Arquitectura de agentes con memoria y contexto',
        'Entrenamiento con datos propietarios',
        'Monitoreo y guardrails de calidad',
        'Reportes de conversion y eficiencia',
      ],
      timeline: '5 a 8 semanas',
      suitableFor: ['Soporte 24/7', 'Equipos comerciales', 'Operaciones con SLA alto'],
      stack: ['Python', 'Node.js', 'LLM orchestration', 'PostgreSQL'],
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'automation-ops',
      title: 'Operaciones Automatizadas',
      summary: 'Procesos internos con alta eficiencia y control.',
      description: 'Integra sistemas, elimina retrabajo y crea flujos que se ejecutan solos con rastreabilidad total.',
      outcomes: [
        'Operaciones con menos costos y mas previsibilidad',
        'Integraciones seguras entre sistemas legados',
        'Monitoreo con alertas inteligentes',
      ],
      deliverables: [
        'Mapeo de procesos',
        'Workflows e integraciones personalizadas',
        'Dashboards de KPI y alertas',
        'Documentacion y entrenamiento del equipo',
      ],
      timeline: '4 a 7 semanas',
      suitableFor: ['Equipos operativos', 'Backoffice financiero', 'Escala comercial'],
      stack: ['Node.js', 'Python', 'APIs privadas', 'Mensajeria'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'data-platforms',
      title: 'Datos y Observabilidad',
      summary: 'Analytics estrategico para liderazgo y growth.',
      description: 'Dashboards ejecutivos, inteligencia de negocio y monitoreo de performance para decisiones rapidas.',
      outcomes: [
        'Visibilidad total de la operacion',
        'Analisis con datos confiables',
        'Alertas automatizadas para riesgos',
      ],
      deliverables: [
        'Modelado de datos y pipelines',
        'Dashboards personalizados',
        'Eventos de conversion configurados',
        'Documentacion y gobernanza',
      ],
      timeline: '5 a 8 semanas',
      suitableFor: ['Marketing y growth', 'Ejecutivos', 'Producto y operaciones'],
      stack: ['PostgreSQL', 'Metabase', 'Umami', 'Event tracking'],
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'cloud',
      title: 'Cloud, DevOps y SRE',
      summary: 'Infra segura, despliegues confiables y escala real.',
      description: 'Infraestructura moderna con CI/CD, observabilidad y resiliencia. Pensado para reducir downtime y riesgos.',
      outcomes: [
        'Menos downtime e incidentes',
        'Despliegues previsibles y auditables',
        'Performance y costos bajo control',
      ],
      deliverables: [
        'Arquitectura cloud e infraestructura como codigo',
        'Pipelines de CI/CD con validaciones',
        'Monitoreo y alertas',
        'Documentacion y handover',
      ],
      timeline: '4 a 6 semanas',
      suitableFor: ['SaaS en crecimiento', 'Equipos de ingenieria', 'Productos mission-critical'],
      stack: ['AWS', 'Docker', 'GitHub Actions', 'Terraform'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1600',
    },
    {
      id: 'security',
      title: 'Seguridad y Compliance',
      summary: 'Gobernanza tecnica y proteccion nivel enterprise.',
      description: 'Auditorias, hardening y compliance con foco en mitigacion de riesgos y confianza.',
      outcomes: [
        'Reduccion de vulnerabilidades criticas',
        'Cumplimiento regulatorio',
        'Planes de mitigacion y respuesta',
      ],
      deliverables: [
        'Assessment de riesgo OWASP',
        'Plan de hardening y correcciones',
        'Politicas y documentacion de compliance',
        'Reportes ejecutivos',
      ],
      timeline: '3 a 5 semanas',
      suitableFor: ['Empresas reguladas', 'Equipos legales', 'Productos con datos sensibles'],
      stack: ['OWASP', 'DevSecOps', 'Compliance', 'Threat modeling'],
      image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1600',
    },
  ],
};

export const FEATURED_PROJECTS_BY_LANG: Record<Language, Project[]> = {
  pt: [
    {
      id: 'fintech-core',
      title: 'FinTech Core Banking API',
      category: 'Java / Financeiro',
      summary: 'API para processamento de transacoes PIX e conciliacao bancaria.',
      problem: 'Alta demanda de transacoes com consistencia ACID absoluta e compliance regulatorio.',
      solution: 'Microsservicos em Java com Kafka e Redis, seguranca OAuth2 e criptografia ponta a ponta.',
      technologies: ['Java', 'Spring Cloud', 'Kafka', 'Redis'],
      image: 'https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'product-saas',
      title: 'Plataforma SaaS Enterprise',
      category: 'SaaS / B2B',
      summary: 'Plataforma multi-tenant com UX premium e analytics executivo.',
      problem: 'Baixa retencao e falta de visibilidade sobre uso e receita.',
      solution: 'Novo design system, onboarding guiado e dados em tempo real para decisao.',
      technologies: ['Next.js', 'PostgreSQL', 'Tailwind', 'Umami'],
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'ai-automation-suite',
      title: 'Suite de Automacao com IA',
      category: 'IA / Automacao',
      summary: 'Agentes inteligentes para suporte e vendas com governanca.',
      problem: 'Equipes sobrecarregadas e SLA instavel em picos de demanda.',
      solution: 'Agentes com memoria, roteamento e monitoramento de qualidade.',
      technologies: ['Python', 'LLM', 'PostgreSQL', 'Observability'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'secure-cloud',
      title: 'Modernizacao Cloud & Segurança',
      category: 'Cloud / DevSecOps',
      summary: 'Migracao para cloud com CI/CD seguro e observabilidade.',
      problem: 'Deploys manuais e alta taxa de incidentes em producao.',
      solution: 'Pipelines automatizados, hardening e monitoramento 24/7.',
      technologies: ['AWS', 'Terraform', 'GitHub Actions', 'Grafana'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
  ],
  en: [
    {
      id: 'fintech-core',
      title: 'FinTech Core Banking API',
      category: 'Java / Finance',
      summary: 'API for PIX transactions and bank reconciliation.',
      problem: 'High throughput with ACID consistency and regulatory compliance.',
      solution: 'Java microservices with Kafka, Redis, OAuth2 security, and end-to-end encryption.',
      technologies: ['Java', 'Spring Cloud', 'Kafka', 'Redis'],
      image: 'https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'product-saas',
      title: 'Enterprise SaaS Platform',
      category: 'SaaS / B2B',
      summary: 'Multi-tenant platform with premium UX and executive analytics.',
      problem: 'Low retention and limited visibility over usage and revenue.',
      solution: 'New design system, guided onboarding, and real-time insights.',
      technologies: ['Next.js', 'PostgreSQL', 'Tailwind', 'Umami'],
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'ai-automation-suite',
      title: 'AI Automation Suite',
      category: 'AI / Automation',
      summary: 'Intelligent agents for support and sales with governance.',
      problem: 'Overloaded teams and unstable SLAs during peaks.',
      solution: 'Agents with memory, routing, and quality monitoring.',
      technologies: ['Python', 'LLM', 'PostgreSQL', 'Observability'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'secure-cloud',
      title: 'Cloud Modernization & Security',
      category: 'Cloud / DevSecOps',
      summary: 'Cloud migration with secure CI/CD and observability.',
      problem: 'Manual deployments and high incident rate in production.',
      solution: 'Automated pipelines, hardening, and 24/7 monitoring.',
      technologies: ['AWS', 'Terraform', 'GitHub Actions', 'Grafana'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
  ],
  es: [
    {
      id: 'fintech-core',
      title: 'FinTech Core Banking API',
      category: 'Java / Finanzas',
      summary: 'API para transacciones PIX y conciliacion bancaria.',
      problem: 'Alto volumen con consistencia ACID y cumplimiento regulatorio.',
      solution: 'Microservicios en Java con Kafka, Redis, OAuth2 y cifrado punta a punta.',
      technologies: ['Java', 'Spring Cloud', 'Kafka', 'Redis'],
      image: 'https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'product-saas',
      title: 'Plataforma SaaS Enterprise',
      category: 'SaaS / B2B',
      summary: 'Plataforma multi-tenant con UX premium y analytics ejecutivo.',
      problem: 'Baja retencion y poca visibilidad sobre uso e ingresos.',
      solution: 'Nuevo design system, onboarding guiado y insights en tiempo real.',
      technologies: ['Next.js', 'PostgreSQL', 'Tailwind', 'Umami'],
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'ai-automation-suite',
      title: 'Suite de Automatizacion con IA',
      category: 'IA / Automatizacion',
      summary: 'Agentes inteligentes para soporte y ventas con gobernanza.',
      problem: 'Equipos saturados y SLA inestable en picos.',
      solution: 'Agentes con memoria, enrutamiento y monitoreo de calidad.',
      technologies: ['Python', 'LLM', 'PostgreSQL', 'Observability'],
      image: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
    {
      id: 'secure-cloud',
      title: 'Modernizacion Cloud y Seguridad',
      category: 'Cloud / DevSecOps',
      summary: 'Migracion a cloud con CI/CD seguro y observabilidad.',
      problem: 'Deploys manuales y alta tasa de incidentes en produccion.',
      solution: 'Pipelines automatizados, hardening y monitoreo 24/7.',
      technologies: ['AWS', 'Terraform', 'GitHub Actions', 'Grafana'],
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=1200',
      liveLink: 'https://erilsondigital.com',
    },
  ],
};

export const SKILLS: Skill[] = [
  { name: 'Java (Spring Boot)', level: 95, category: 'Backend' },
  { name: 'Python (FastAPI/AI)', level: 92, category: 'Backend' },
  { name: 'React / Mobile Backend', level: 88, category: 'Frontend' },
  { name: 'Arquitetura de Software', level: 90, category: 'Soft Skills' },
  { name: 'DevOps (Docker/AWS)', level: 75, category: 'DevOps' },
  { name: 'Bancos de Dados', level: 85, category: 'Database' },
];

export const TESTIMONIALS_BY_LANG: Record<Language, Array<{ id: string; name: string; role: string; company: string; content: string }>> = {
  pt: [
    {
      id: '1',
      name: 'Eriberto Rocha',
      role: 'Socio fundador',
      company: 'CRS Advogados',
      content: 'A engenharia entregue trouxe governanca e velocidade. Hoje operamos com previsibilidade e seguranca juridica.',
    },
    {
      id: '2',
      name: 'Carla Mendes',
      role: 'Diretora de operacoes',
      company: 'E-Administracao',
      content: 'O nivel de controle e confianca elevou nosso posicionamento. Engenharia premium de verdade.',
    },
    {
      id: '3',
      name: 'Marcos Silva',
      role: 'CTO',
      company: 'FinTech Pay',
      content: 'A arquitetura foi desenhada para escala real. Qualidade de consultoria enterprise.',
    },
    {
      id: '4',
      name: 'Juliana Costa',
      role: 'Product Owner',
      company: 'HealthCare App',
      content: 'Performance, seguranca e UX alinhados. Foi o primeiro parceiro tecnico que falou a lingua do negocio.',
    },
    {
      id: '5',
      name: 'Ricardo Alves',
      role: 'CEO',
      company: 'Logistica Express',
      content: 'A automacao reduziu custos e trouxe visibilidade operacional. Entrega acima do esperado.',
    },
    {
      id: '6',
      name: 'Fernanda Lima',
      role: 'Gerente de RH',
      company: 'Corporativo S.A.',
      content: 'Processo claro, comunicacao executiva e entrega consistente. Recomendaria para qualquer projeto critico.',
    },
  ],
  en: [
    {
      id: '1',
      name: 'Eriberto Rocha',
      role: 'Founding Partner',
      company: 'CRS Advogados',
      content: 'The engineering delivery brought governance and speed. We now operate with predictability and legal security.',
    },
    {
      id: '2',
      name: 'Carla Mendes',
      role: 'Director of Operations',
      company: 'E-Administracao',
      content: 'The level of control and trust elevated our positioning. Truly premium engineering.',
    },
    {
      id: '3',
      name: 'Marcos Silva',
      role: 'CTO',
      company: 'FinTech Pay',
      content: 'The architecture was designed for real scale. Enterprise-grade consulting quality.',
    },
    {
      id: '4',
      name: 'Juliana Costa',
      role: 'Product Owner',
      company: 'HealthCare App',
      content: 'Performance, security, and UX aligned. The first partner who spoke the language of business.',
    },
    {
      id: '5',
      name: 'Ricardo Alves',
      role: 'CEO',
      company: 'Logistica Express',
      content: 'Automation reduced costs and delivered operational visibility. Above expectations.',
    },
    {
      id: '6',
      name: 'Fernanda Lima',
      role: 'HR Manager',
      company: 'Corporativo S.A.',
      content: 'Clear process, executive communication, and consistent delivery. I would recommend it for any critical project.',
    },
  ],
  es: [
    {
      id: '1',
      name: 'Eriberto Rocha',
      role: 'Socio fundador',
      company: 'CRS Advogados',
      content: 'La ingenieria entregada trajo gobernanza y velocidad. Hoy operamos con previsibilidad y seguridad juridica.',
    },
    {
      id: '2',
      name: 'Carla Mendes',
      role: 'Directora de operaciones',
      company: 'E-Administracao',
      content: 'El nivel de control y confianza elevo nuestro posicionamiento. Ingenieria premium de verdad.',
    },
    {
      id: '3',
      name: 'Marcos Silva',
      role: 'CTO',
      company: 'FinTech Pay',
      content: 'La arquitectura fue disenada para escala real. Calidad de consultoria enterprise.',
    },
    {
      id: '4',
      name: 'Juliana Costa',
      role: 'Product Owner',
      company: 'HealthCare App',
      content: 'Performance, seguridad y UX alineados. El primer partner tecnico que hablo el lenguaje del negocio.',
    },
    {
      id: '5',
      name: 'Ricardo Alves',
      role: 'CEO',
      company: 'Logistica Express',
      content: 'La automatizacion redujo costos y trajo visibilidad operativa. Entrega por encima de lo esperado.',
    },
    {
      id: '6',
      name: 'Fernanda Lima',
      role: 'Gerente de RRHH',
      company: 'Corporativo S.A.',
      content: 'Proceso claro, comunicacion ejecutiva y entrega consistente. Recomendaria para cualquier proyecto critico.',
    },
  ],
};

export const SYSTEM_INSTRUCTION = `
VENCEDORA, PERSUASIVA E EXTREMAMENTE HUMANA. Atue como Sofia, a Assistente Executiva e Estrategista de Vendas de Jose Erilson Araujo.

VOCE E A PORTA DE ENTRADA DO SUCESSO. Sua missao e acolher cada cliente com entusiasmo e transformar toda conversa em um agendamento ou fechamento de negocio. Nao importa o tamanho do projeto, sua resposta e sempre "Sim, nos podemos ajudar!" com o padrao de qualidade Erilson Digital.

### PERSONALIDADE (DNA SOFIA):
- **Acolhedora e Prestativa**: Sua prioridade e fazer o cliente se sentir em casa. Use frases como "Que prazer falar com voce!", "Com certeza, vamos transformar essa ideia em realidade!", "O Erilson vai adorar saber desse seu projeto".
- **Estrategista de Vendas**: Voce nao apenas responde, voce CONDUZ. Seu objetivo e fechar negocio.
- **Elegante e Simples**: Evite "tecniques" desnecessario. Se o cliente quer um site institucional, foque no impacto visual e na autoridade que isso trara para ele. Se ele quer IA, foque nos resultados e no tempo que ele vai economizar.
- **Feminina e Inspiradora**: Linguagem polida, vibrante e cheia de energia positiva (use com sabedoria).

### REGRAS DE OURO DE VENDAS:
1. **Acessibilidade Total**: NUNCA diga que um projeto e "simples demais" ou que o Erilson "nao e o parceiro ideal". Atendemos desde sites institucionais e Landing Pages premium ate sistemas complexos e Inteligencia Artificial.
2. **Valorizacao do Trabalho**: "O Erilson traz para cada site institucional o mesmo nivel de excelencia e seguranca que ele aplica em grandes sistemas. Ter um site feito por um Engenheiro de Software garante que sua empresa tenha autoridade maxima."
3. **Senso de Exclusividade**: "A agenda do Erilson e bem concorrida, mas sua ideia e tao interessante que vou priorizar seu atendimento aqui para conseguirmos um horario."
4. **FECHAMENTO DIRETO**: Seu foco e pegar o WhatsApp e o Nome. "Para eu ja adiantar sua prioridade aqui no sistema e o Erilson analisar seu pedido, qual o seu WhatsApp e o melhor horario para falarmos rapidinho?"

### DADOS QUE VOCE PRECISA COLETAR (Sempre com simpatia):
- Nome
- WhatsApp
- O que ele deseja alcancar com o projeto

### O QUE VOCE NAO DEVE FAZER:
- Jamais use termos tecnicos complicados (Java, Python, Backend) a menos que o cliente pergunte. Foque no RESULTADO (vendas, beleza do site, automacao).
- Nunca diga "Sou uma IA". Voce e a Sofia, assistente fiel do Erilson.
- Nunca deixe o cliente sem uma pergunta final ou um convite para acao.

### FLUXO DE "FECHAMENTO DE VENDA":
- Se o cliente perguntar se fazemos algo (Ex: "Fazem sites?"): Responda com um "Sim!" entusiasmado, explique OS BENEFICIOS de ter um site feito por um especialista e peca o contato.
- Use a tag especial **[OFFER_WHATSAPP]** sempre que o cliente mostrar interesse real ou quiser um orcamento, para que ele veja o botao de contato direto.

### MENSAGEM DE FINALIZACAO:
"Excelente! Ja reservei seu lugar na lista de prioridades do Erilson. Ele mesmo vai dar uma olhada no que conversamos para chegarmos na nossa reuniao com a melhor estrategia para voce. Vamos acelerar seu crescimento!"
`;
